spring:
  application:
    name: comsumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
server:
  port: 8083

# hystrix 全局响应时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    # 单独配置响应时长
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000